// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as ProjectCard from "../components/ProjectCard.mjs";

function $$default(props) {
  console.log(props);
  return React.createElement("div", undefined, React.createElement("div", {
                  className: "lg:text-center mb-10 mt-10"
                }, React.createElement("h2", {
                      className: "text-base text-indigo-600 font-semibold tracking-wide uppercase"
                    }, "Project Exhibition"), React.createElement("p", {
                      className: "mt-2 text-3xl leading-8 font-extrabold tracking-tight text-gray-900 sm:text-4xl"
                    }, " Welcome to HomeSit Institute"), React.createElement("p", {
                      className: "mt-4 max-w-2xl text-xl text-gray-500 lg:mx-auto"
                    }, "The team of teachers will evaluate your project, and if the evaluation has a graduation level, you can get a graduation certificate signed by the principal (that is, me) and all teachers involved in the development of your project")), React.createElement("div", {
                  className: "grid grid-cols-3 gap-3 space-x-4"
                }, React.createElement(ProjectCard.make, {
                      img: "/React.png",
                      title: "Progarmming for React",
                      info: "It is thought that the best course in the world"
                    }), React.createElement(ProjectCard.make, {
                      img: "/static/hsit.svg",
                      title: "DAXUE",
                      info: "hhaa"
                    }), React.createElement(ProjectCard.make, {
                      img: "/static/hsit.svg",
                      title: "DAXUE",
                      info: "hhaa"
                    })));
}

function getServerSideProps(_ctx) {
  return Promise.resolve({
              props: {
                msg: "This page was rendered with getServerSideProps. You can find the source code here:2 ",
                href: "https://github.com/ryyppy/nextjs-default/tree/master/src/Examples.res"
              }
            });
}

export {
  $$default ,
  $$default as default,
  getServerSideProps ,
  
}
/* react Not a pure module */
