// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as BigPostCard from "../components/BigPostCard.mjs";

function $$default(props) {
  return React.createElement("div", undefined, React.createElement(BigPostCard.make, {
                  text: React.createElement("h1", {
                        className: "text-white place-self-center"
                      }, "欢迎来到俺们大学"),
                  image: React.createElement("img", {
                        src: "/static/hsit.svg"
                      })
                }), React.createElement("div", {
                  className: " bg-blue-500 text-white text-xl grid grid-cols-1 md:grid-cols-2 text-center"
                }, React.createElement("div", {
                      className: "hover:bg-blue-800"
                    }, "aaa"), React.createElement("div", {
                      className: "hover:bg-blue-800"
                    }, "bbb"), React.createElement("div", {
                      className: "hover:bg-blue-800"
                    }, "ccc"), React.createElement("div", {
                      className: "hover:bg-blue-800"
                    }, "ddd")), React.createElement("h1", {
                  className: "text-gray-500"
                }, props.msg));
}

function getServerSideProps(_ctx) {
  return Promise.resolve({
              props: {
                msg: "server side"
              }
            });
}

export {
  $$default ,
  $$default as default,
  getServerSideProps ,
  
}
/* react Not a pure module */
