// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as PostCard from "../components/PostCard.mjs";
import Head from "next/head";
import * as BigPostCard from "../components/BigPostCard.mjs";

function $$default(props) {
  console.log(props);
  return React.createElement("div", undefined, React.createElement(Head, {
                  children: React.createElement("title", undefined, "HSIT 赫姆席特大学官网")
                }), React.createElement(BigPostCard.make, {
                  text: React.createElement("h1", {
                        className: "text-white place-self-center"
                      }, "欢迎来到俺们大学"),
                  image: React.createElement("img", {
                        src: "/static/hsit.svg"
                      })
                }), React.createElement("div", {
                  className: " bg-blue-500 text-white text-xl grid grid-cols-1 md:grid-cols-2 text-center"
                }, React.createElement("div", {
                      className: "hover:bg-blue-800"
                    }, "aaa"), React.createElement("div", {
                      className: "hover:bg-blue-800"
                    }, "bbb"), React.createElement("div", {
                      className: "hover:bg-blue-800"
                    }, "ccc"), React.createElement("div", {
                      className: "hover:bg-blue-800"
                    }, "ddd")), React.createElement("div", {
                  className: "bg-gray-100 p-10 grid grid-cols-1 md:grid-cols-2 gap-5"
                }, React.createElement(PostCard.make, {
                      icon: "/static/hsit.svg",
                      title: "title",
                      info: "info",
                      children: React.createElement("button", {
                            className: " bg-blue-500 p-2 hover:bg-blue-800 rounded-full text-white"
                          }, "click me")
                    }), React.createElement(PostCard.make, {
                      icon: "/static/hsit.svg",
                      title: "title",
                      info: "info",
                      children: React.createElement("button", {
                            className: " bg-blue-500 p-2 hover:bg-blue-800 rounded-full text-white"
                          }, "click me")
                    }), React.createElement(PostCard.make, {
                      icon: "/static/hsit.svg",
                      title: "title",
                      info: "info",
                      children: React.createElement("button", {
                            className: " bg-blue-500 p-2 hover:bg-blue-800 rounded-full text-white"
                          }, "click me")
                    }), React.createElement(PostCard.make, {
                      icon: "/static/hsit.svg",
                      title: "title",
                      info: "info",
                      children: React.createElement("button", {
                            className: " bg-blue-500 p-2 hover:bg-blue-800 rounded-full text-white"
                          }, "click me")
                    })));
}

function getServerSideProps(_ctx) {
  return Promise.resolve({
              props: {
                msg: "server side"
              }
            });
}

export {
  $$default ,
  $$default as default,
  getServerSideProps ,
  
}
/* react Not a pure module */
