// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function BigPostCard(Props) {
  var text = Props.text;
  var image = Props.image;
  return React.createElement("div", undefined, React.createElement("div", {
                  className: "\n            bg-gray-100\n            grid \n                grid-cols-1 \n                md:grid-cols-2 \n                lg:grid-cols-2 \n        "
                }, React.createElement("div", {
                      className: "bg-gray-600 text-white text-center text-6xl min-h-full grid grid-cols-1"
                    }, text), React.createElement("div", {
                      className: ""
                    }, image)));
}

var make = BigPostCard;

export {
  make ,
  
}
/* react Not a pure module */
