// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function PostCard(Props) {
  var icon = Props.icon;
  var title = Props.title;
  var info = Props.info;
  var children = Props.children;
  return React.createElement("div", {
              className: "border bg-white rounded-md p-3 m-3 drop-shadow-md"
            }, React.createElement("img", {
                  className: "border-b border-gray-400",
                  src: icon
                }), React.createElement("h2", {
                  className: "text-2xl m-2"
                }, title), React.createElement("h3", {
                  className: "text-gray-400 m-3"
                }, info), React.createElement("div", {
                  className: " rounded-xl p-3 w-full"
                }, children));
}

var make = PostCard;

export {
  make ,
  
}
/* react Not a pure module */
