// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import Link from "next/link";

function MainLayout$Navigation(Props) {
  return React.createElement("nav", {
              className: " bg-white sticky top-0 z-50 p-2 h-20 flex border-b border-gray-200 justify-between items-center text-sm\n    "
            }, React.createElement(Link, {
                  href: "/",
                  children: React.createElement("a", {
                        className: "flex items-center w-1/2"
                      }, React.createElement("img", {
                            className: "w-28",
                            src: "/static/hsit.svg"
                          }), React.createElement("span", {
                            className: "text-xl ml-2 align-middle font-semibold hidden sm:inline"
                          }, "HomeSit Institute of Technology"))
                }), React.createElement("div", {
                  className: "flex w-1/2 justify-end"
                }, React.createElement("div", {
                      className: "hidden md:inline"
                    }, React.createElement(Link, {
                          href: "/",
                          children: React.createElement("a", {
                                className: "px-3"
                              }, "Home")
                        }), React.createElement(Link, {
                          href: "/examples",
                          children: React.createElement("a", {
                                className: "px-3"
                              }, "Examples")
                        })), React.createElement("div", {
                      className: "inline md:hidden"
                    }, "mobile")));
}

function MainLayout$Footer(Props) {
  return React.createElement("nav", {
              className: "border-t border-gray-400 bg-gray-300"
            }, React.createElement("div", {
                  className: "h-20"
                }));
}

function MainLayout(Props) {
  var children = Props.children;
  var minWidth = {
    minWidth: "20rem"
  };
  return React.createElement("div", {
              className: "flex lg:justify-center",
              style: minWidth
            }, React.createElement("div", {
                  className: " max-w-6xl w-full lg:w-5/6 text-gray-900 font-base"
                }, React.createElement(MainLayout$Navigation, {}), React.createElement("main", {
                      className: "mt-4 mx-4 min-h-screen"
                    }, children), React.createElement(MainLayout$Footer, {})));
}

var make = MainLayout;

export {
  make ,
  
}
/* react Not a pure module */
